name: Bug report
description: Create a report to help us improve
title: ":beetle: [BUG]: "
labels: ['kind/bug']
body:
- type: textarea
  id: what-should-happen
  attributes:
    label: Describe the bug
    placeholder: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: Expected Behavior
    placeholder: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
  validations:
    required: true
- type: textarea
  id: version
  attributes:
    label: Relevant Versions
    placeholder: v1.22.0
  validations:
    required: true
- type: textarea
  id: additional-info
  attributes:
    label: Additonal Context and Screenshots
    placeholder: Add any other context about the problem here or add screenshots to help explain your problem (if applicable).
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
